name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Locate gradlew
        run: |
          echo "===== LIST ROOT ====="
          ls -la
          echo "===== FIND gradlew ====="
          find . -maxdepth 6 -name "gradlew" -print
          echo "===== FIND settings.gradle ====="
          find . -maxdepth 6 -name "settings.gradle" -print
          echo "===== FIND build.gradle ====="
          find . -maxdepth 6 -name "build.gradle" -print

      - name: Finish debug
        run: echo "Locate step finished"


 - name: Build Debug APK
   run: cd build-apk/android && ./gradlew assembleDebug

 - name: Upload APK
   uses: actions/upload-artifact@v4
     with:
       name: SoloVideoClub-debug-apk
       path: build-apk/android/app/build/outputs/apk/debug/app-debug.apk


